### ISSUE TITLE
SwaggerHub import fails

### ISSUE THREAD

**Issue by fehguy** [SmartBear/readyapi-swaggerhub-plugin#12]
Importing from a public SwaggerHub definition seems to get the import tool stuck in a loop.  Try selecting `iot-api` from the list of apis, any version.  Ready hangs and needs to be force-quit

**Comment by olensmar** [comment]
unfortunately I couldn't reproduce this - see attached screenshot
![image](https://cloud.githubusercontent.com/assets/1917063/20532192/68cc4f22-b0d9-11e6-858a-964940175652.png) 

Which versions of the Swagger and SwaggerHub plugins did you have installed?

**Comment by fehguy** [comment]
I'm using the vanilla-install of R!A 1.9.0.  Should I try another version?

**Comment by olensmar** [comment]
no - that's the one I was using also - but I may have newer plugins locally from other installations (since they share the plugins folder) - could you just open the plugin-manager and let me know which versions of these plugins that seem to be installed?

**Comment by fehguy** [comment]
I just tried again and I may know what happened.  I think a dialog box popped up behind the R!A window and it was waiting for some user input (file save location).  It seemed to work this time.

Plugin version is 1.1.1 FWIW.

I think we can close this and I'll reopen if I can reproduce it again.

**Comment by olensmar** [comment]
ok thanks
