### ISSUE TITLE
Import Swagger Definition dialog resizes wrong

### ISSUE THREAD

**Issue by MaximBuyanov** [SmartBear/readyapi-swaggerhub-plugin#3]
Steps to reproduce:
1. Right click on project and select Import from SwaggerHub 
2. Try to resize dialog to view more APIs

![20151001-1300 1](https://cloud.githubusercontent.com/assets/7962140/10331216/3c986b4e-6cdc-11e5-8171-db71428bbcc7.gif)

See https://smartbear.atlassian.net/browse/SOAPUIOS-172 for details

**Comment by olensmar** [comment]
thanks - this is unfortunately how the dialog-subsystem works in Ready!API - I can't fix it in the plugin
