### ISSUE TITLE
Resize API Key edit field

### ISSUE THREAD

**Issue by MaximBuyanov** [SmartBear/readyapi-swaggerhub-plugin#5]
![dialog](https://cloud.githubusercontent.com/assets/7962140/10331306/efdef312-6cdc-11e5-942d-f4c106060ede.png)

See https://smartbear.atlassian.net/browse/SOAPUIOS-174 for details

**Comment by olensmar** [comment]
this is the size of password fields in Ready! API dialogs - there is no documented way to resizing it at this point
