### ISSUE TITLE
Delete label 'search' near button 'search'

### ISSUE THREAD

**Issue by MaximBuyanov** [SmartBear/readyapi-swaggerhub-plugin#7]
![search](https://cloud.githubusercontent.com/assets/7962140/10331372/7b829e28-6cdd-11e5-873c-3cb13ef34b7e.png)
See https://smartbear.atlassian.net/browse/SOAPUIOS-176 for details

**Comment by olensmar** [comment]
hmm... this doesn't seem to be possible either with the dialog subsystem - I'm almost thinking I should just create a custom dialog...
